# 稀疏 vs. 稠密

In [1]:
from scipy.sparse import csr_matrix
import torch


In [3]:
# 原始稠密数据
dense = [[0, 0, 3], [0, 0, 0]]

# 创建稀疏矩阵
sparse = csr_matrix(dense) # csr stand for Compressed Sparse Row
print("稀疏矩阵:\n", sparse)

稀疏矩阵:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1 stored elements and shape (2, 3)>
  Coords	Values
  (0, 2)	3


In [4]:
# 转成稠密
dense_again = sparse.toarray()
print("toarray() 结果:\n", dense_again)

toarray() 结果:
 [[0 0 3]
 [0 0 0]]


In [5]:
# 转成 PyTorch tensor
tensor = torch.tensor(dense_again, dtype=torch.float32)
print("PyTorch tensor:\n", tensor)

PyTorch tensor:
 tensor([[0., 0., 3.],
        [0., 0., 0.]])


# Squeeze

.squeeze() 删除所有维度为1的维度（比如从 (1, 2048) 变成 (2048,)）

In [1]:
import torch

x = torch.randn(1, 3, 1)
print("原始形状：", x.shape)  # torch.Size([1, 3, 1])

y = x.squeeze()
print("squeeze 后形状：", y.shape)  # torch.Size([3])


原始形状： torch.Size([1, 3, 1])
squeeze 后形状： torch.Size([3])


.squeeze() 会自动把所有 维度为 1 的轴删掉。

上面例子中删掉了第 0 维和第 2 维，变成了一维 [3]

# .flatten()

把所有维度拉平成一个维度

In [3]:
x = torch.randn(1, 3, 1)
print("原始形状：", x.shape)  # torch.Size([1, 3, 1])

y = x.flatten()
print("flatten 后形状：", y.shape)  # torch.Size([3])

原始形状： torch.Size([1, 3, 1])
flatten 后形状： torch.Size([3])


In [4]:
x = torch.randn(2, 3, 4)  # 形状是 (2, 3, 4)
print("原始形状：", x.shape)  # torch.Size([2, 3, 4])

# flatten
y1 = x.flatten()
print("flatten 后：", y1.shape)  # torch.Size([24])

# squeeze（啥都不变，因为没有维度为1）
y2 = x.squeeze()
print("squeeze 后：", y2.shape)  # torch.Size([2, 3, 4])

原始形状： torch.Size([2, 3, 4])
flatten 后： torch.Size([24])
squeeze 后： torch.Size([2, 3, 4])


# 如何确认是否和 VPN 有关？

In [1]:
import requests

proxies = {
    "http": "http://127.0.0.1:7890",
    "https": "http://127.0.0.1:7890",
}

resp = requests.get("https://httpbin.org/ip", proxies=proxies, verify=False)
print(resp.text)


c:\Users\Cavendishes\.conda\envs\tahoe-cvae\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


{
  "origin": "62.192.175.4"
}

